startproject/appointment/urls.py
from django.conf.urls import url

from . import views

app_name = 'appointment'
urlpatterns = [
    url(r'^acm/$', views.get_Acm, name='acm_get_acm'),
    url(r'^acm/detail/(\d+)/$', views.get_Acm_detail, name='acm_get_detail'),
    url(r'^lecture/$', views.get_Lecture, name='lecture_get_lecture'),
    url(r'^lecture/detail/(\d+)/$', views.get_Lecture_detail, name='lecture_get_detail'),
    url(r'^station/$', views.get_Station, name='station_get_station'),
    url(r'^station/detail/(\d+)/$', views.get_Station_detail, name='station_get_detail'),
]

startproject/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^register/', include('register.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls')),
    url(r'^appointment/', include('appointment.urls')),
]

startproject/news/urls.py
from django.conf.urls import url

from . import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.get_news, name='news_get_news'),
    url(r'^detail/(\d+)/$', views.get_detail, name='news_get_detail'),
]

startproject/appointment/models.py
# Create your models here.

from django.db import models

from register.models import User

class Acm(models.Model):
    '''
    '''

    member = models.CharField('成员', max_length=32)
    gender = models.CharField('性别', max_length=16)
    major = models.CharField('专业', max_length=16)
    phone = models.CharField('电话',max_length=11)  # 字符型，必须有个参数max_length字符最大值
    email = models.EmailField('邮箱')
    awards = models.TextField('获奖')
    introduction = models.TextField('介绍')

    def __str__(self):
        return self.member

class Station(models.Model):
    '''
    '''

    project_name = models.CharField('应用名称', max_length=32)
    introduction = models.TextField('介绍')

    def __str__(self):
        return self.project_name

class Lecture(models.Model):
    '''
    '''

    theme = models.CharField('讲座主题', max_length=140)
    professor = models.CharField('教授', max_length=32)
    time = models.CharField('时间', max_length=32)
    place = models.CharField('地点', max_length=32)
    introduction = models.TextField('介绍')

    def __str__(self):
        return self.theme

class appoint_acm(models.Model):
    '''
    '''

    acm = models.ForeignKey(Acm, verbose_name='竞赛生')

    #x_id = models.CharField('预约对象的id', max_length=9)
    #x_type = models.CharField('预约对象的类型', max_length=9)
    start_time = models.DateField('开始时间')
    people = models.CharField('预约人数', max_length=10)

    #user = models.ForeignKey(User, verbose_name='用户')
    name = models.CharField('用户名称', max_length=20)
    email = models.EmailField('邮箱')

    def __str__(self):
        return self.name

class appoint_lecture(models.Model):
    '''
    '''

    lecture = models.ForeignKey(Lecture, verbose_name='讲座')

    start_time = models.DateField('开始时间')
    people = models.CharField('预约人数', max_length=10)

    #user = models.ForeignKey(User, verbose_name='用户')
    name = models.CharField('用户名称', max_length=20)
    email = models.EmailField('邮箱')

    def __str__(self):
        return self.name

class appoint_station(models.Model):
    '''
    '''

    station = models.ForeignKey(Station, verbose_name='讲座')

    start_time = models.DateField('开始时间')
    people = models.CharField('预约人数', max_length=10)

    #user = models.ForeignKey(User, verbose_name='用户')
    name = models.CharField('用户名称', max_length=20)
    email = models.EmailField('邮箱')

    def __str__(self):
        return self.name

startproject/appointment/forms.py
from django import forms
from django.http import Http404

class AppointAcmForm(forms.Form):
    """
    预约表单
    """

    '''
    school = forms.CharField(label='学校', max_length=20, error_messages={
        'required': '请填写您的学校',
        'max_length': '学校太长'
    })

    phone = forms.CharField(label='电话', max_length=11, error_messages={
        'required': '请填写您的电话',
        'max_length': '电话太长'
    })
    
    user_id = forms.CharField(label='用户ID', error_messages={
        'required': '请填写您的用户id',
        'invalid': 'id格式不正确'
    })
    '''

    name = forms.CharField(label='您的称呼', max_length=20, error_messages={
        'required': '请填写您的称呼',
        'max_length': '称呼太长'
    })

    email = forms.EmailField(label='联系邮箱', error_messages={
        'required': '请填写您的邮箱',
        'invalid': '邮箱格式不正确'
    })

    start_time = forms.DateField(label='开始时间', widget=forms.SelectDateWidget, error_messages={
        'required': '请填写您的预约开始时间',
        'invalid': '时间格式不正确'
    })

    people = forms.CharField(label='预约人数', error_messages={
        'required': '请填写您的预约人数',
    })


class AppointLectureForm(forms.Form):
    """
    预约表单
    """

    name = forms.CharField(label='您的称呼', max_length=20, error_messages={
        'required': '请填写您的称呼',
        'max_length': '称呼太长'
    })

    email = forms.EmailField(label='联系邮箱', error_messages={
        'required': '请填写您的邮箱',
        'invalid': '邮箱格式不正确'
    })

    start_time = forms.DateField(label='开始时间', widget=forms.SelectDateWidget, error_messages={
        'required': '请填写您的预约开始时间',
        'invalid': '时间格式不正确'
    })

    people = forms.CharField(label='预约人数', error_messages={
        'required': '请填写您的预约人数',
    })

class AppointStationForm(forms.Form):
    """
    预约表单
    """

    name = forms.CharField(label='您的称呼', max_length=20, error_messages={
        'required': '请填写您的称呼',
        'max_length': '称呼太长'
    })

    email = forms.EmailField(label='联系邮箱', error_messages={
        'required': '请填写您的邮箱',
        'invalid': '邮箱格式不正确'
    })

    start_time = forms.DateField(label='开始时间', widget=forms.SelectDateWidget, error_messages={
        'required': '请填写您的预约开始时间',
        'invalid': '时间格式不正确'
    })

    people = forms.CharField(label='预约人数', error_messages={
        'required': '请填写您的预约人数',
    })

startproject/appointment/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse,HttpResponseRedirect


from .models import appoint_acm, appoint_lecture, appoint_station, Acm, Station, Lecture
from register.models import User
from .forms import AppointAcmForm, AppointLectureForm, AppointStationForm

# Create your views here.

def get_Acm(request):
    ctx = {
        'acm': Acm.objects.all()
    }
    return render(request, 'appointment/acm-list.html', ctx)

def get_Acm_detail(request, acm_id):
    name = request.session.get('username','')
    #name = response.get_cookie('username')
    try:
        acm = Acm.objects.get(id=acm_id)
    except Acm.DoesNotExist:
        raise Http404

    if request.method == 'GET':
        #form = AppointAcmForm()
        form = AppointAcmForm(
            initial={'name': name}
        )
        #form.name = name
        #appoint_acm.name = name
        #request.session['appoint_acm.user_id'] = User_id
    else:
        form = AppointAcmForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            cleaned_data['acm'] = acm
            appoint_acm.objects.create(**cleaned_data)

    ctx = {
        'acm': acm,
        'appoint': appoint_acm,
        'form': form,
    }

    #response = HttpResponse('appointment/acm-detail.html')
    #response.set_cookie("User.username", appoint_acm.name)
    #if "username" in request.COOKIES:
        #appoint_acm.name = request.COOKIES["username"]

    return render(request, 'appointment/acm-detail.html', ctx)

def get_Lecture(request):
    ctx = {
        'lecture': Lecture.objects.all()
    }
    return render(request, 'appointment/lecture-list.html', ctx)

def get_Lecture_detail(request, lecture_id):
    name = request.session.get('username','')
    try:
        lecture = Lecture.objects.get(id=lecture_id)
    except Lecture.DoesNotExist:
        raise Http404

    if request.method == 'GET':
        form = AppointLectureForm(
            initial={'name': name}
        )
    else:
        form = AppointLectureForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            cleaned_data['lecture'] = lecture
            appoint_lecture.objects.create(**cleaned_data)

    ctx = {
        'lecture': lecture,
        'appoint': appoint_lecture,
        'form': form,
    }

    return render(request, 'appointment/lecture-detail.html', ctx)

def get_Station(request):
    ctx = {
        'station': Station.objects.all()
    }
    return render(request, 'appointment/station-list.html', ctx)

def get_Station_detail(request, station_id):
    name = request.session.get('username','')
    try:
        station = Station.objects.get(id=station_id)
    except Station.DoesNotExist:
        raise Http404

    if request.method == 'GET':
        form = AppointStationForm(
            initial={'name': name}
        )
    else:
        form = AppointStationForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            cleaned_data['station'] = station
            appoint_lecture.objects.create(**cleaned_data)

    ctx = {
        'station': station,
        'appoint': appoint_station,
        'form': form,
    }
    return render(request, 'appointment/station-detail.html', ctx)

startproject/appointment/templates/appointment/acm-detail.html
<!DOCTYPE HTML>

<html xmlns="http://www.w3.org/1999/html">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>队员详细信息</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="复旦大学计算机科学技术学院与上海高中交流辅导平台" />
	<meta name="author" content="Caroline" />

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

    {%load staticfiles%}

	<!-- Animate.css -->
	<link rel="stylesheet" href="{%static "css/animate.css"%}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{%static "css/icomoon.css"%}">
	<!-- Themify Icons-->
	<link rel="stylesheet" href="{%static "css/themify-icons.css"%}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{%static "css/bootstrap.css"%}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{%static "css/magnific-popup.css"%}">

	<!-- Bootstrap DateTimePicker -->
	<link rel="stylesheet" href="{%static "css/bootstrap-datetimepicker.min.css"%}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{%static "css/owl.carousel.min.css"%}">
	<link rel="stylesheet" href="{%static "css/owl.theme.default.min.css"%}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{%static "css/style.css"%}">

	<!-- Modernizr JS -->
	<script src="{%static "js/modernizr-2.6.2.min.js"%}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{%static "js/respond.min.js"%}"></script>
	<![endif]-->

	</head>
	<body>

	<div class="gtco-loader"></div>

	<div id="page">

	<!-- <div class="page-inner"> -->
	<nav class="gtco-nav" role="navigation">
		<div class="gtco-container">
			<div class="row">
				<div class="col-sm-4 col-xs-12">
					<div id="gtco-logo"><a href="http://127.0.0.1:8000/register/index">Computer Science <em>.</em></a></div>
				</div>
				<div class="col-xs-8 text-right menu-1">
					<ul>
						<li><a href="http://127.0.0.1:8000/news">News</a></li>
						<li class="has-dropdown">
							<a href="services.html">Appointment</a>
							<ul class="dropdown">
								<li><a href="http://127.0.0.1:8000/appointment/acm/">ACM Tutoring</a></li>
								<li><a href="http://127.0.0.1:8000/appointment/lecture/">Lecture</a></li>
								<li><a href="http://127.0.0.1:8000/appointment/station/">Science and Technology Station</a></li>
							</ul>
						</li>
                        <li><a href="contact.html">Contact</a></li>
						<li class="btn-cta"><a href="http://127.0.0.1:8000/register/"><span>Log out</span></a></li>
					</ul>
				</div>
			</div>

		</div>
	</nav>


		<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(/static/images/acm_background.png)" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">

					<div class="row row-mt-15em">
						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
							<span class="intro-text-small">Created by <a target="_blank">Caroline</a></span>
							<h1 class="cursive-font">Coding makes me happy!</h1>
						</div>
					</div>

				</div>
			</div>
		</div>
	</header>

        <div id="gtco-counter" class="gtco-section">
		<div class="gtco-container">

			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading animate-box">
					<h2 class="cursive-font primary-color">ACM members details</h2>
					<p>Some information.</p>
				</div>
			</div>

			<div class="row">
                <div class="col-sm-12 col-md-4 col-lg-4" >
                    <div class="thumbnail">
                        <a href="#" title="' . $result['StuNAME'] . '" target="_blank">
                            <img id = "acm-img{{acm.id}}" src="{%static 'images/acm_'%}" alt="Image" class="img-responsive" >
                            <script>
                                document.getElementById("acm-img{{acm.id}}").src+={{ acm.id }}+'.jpg'
                            </script>
                        </a>
                        <div class="caption">
                            <h3 style="display:inline-block">
                                <a href="#" title="{{acm.member}}" target="_blank">
                                    {{acm.member}}
                                </a>
                            </h3>
                            <h5>{{acm.gender}}     {{acm.major}}<br></h5>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-8 col-lg-8" style="padding-right: 50px">
                    <div style="margin-bottom: 30px">
                        <h5>邮箱： {{ acm.email }}</h5>
                        <h5>电话： {{ acm.phone }}</h5>
                    </div>
                    <hr>
                    <div  style="margin-bottom: 30px">
                        <p>
                            个人简介：</p>
                        <p>{{ acm.introduction }}</p>
                        </p>
                    </div>
                    <hr>
                    <div  style="margin-bottom: 30px">
                        <p>{{ acm.awards }}<br>
                        </p>
                    </div>
					<hr>

					<p> 预约该成员： <br></p>

                    <form action="{% url 'appointment:acm_get_detail' acm.id %}"  method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="input-field" style="padding-top: 10px">
                            {{ field.label }}: {{ field }}
                        </div>
                        <div class="error" style="color: red;">
                            {{ field.errors }}
                        </div>
                        {% endfor %}

                        <button class="btn btn-primary" type="submit" onclick="alert('预约成功！');" style="margin-top: 15px">预约</button>
                    </form>
                </div>
			</div>
		</div>
	</div>


	<footer id="gtco-footer" role="contentinfo" style="background-image: url(/static/images/img_bg_1.jpg)" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row row-pb-md">

				<div class="col-md-12 text-center">
					<div class="gtco-widget">
						<h3>Get In Touch</h3>
						<ul class="gtco-quick-contact">
							<li><a href="#"><i class="icon-phone"></i> +1 234 567 890</a></li>
							<li><a href="#"><i class="icon-mail2"></i> rshcaroline@163.com</a></li>
							<li><a href="#"><i class="icon-chat"></i> Live Chat</a></li>
						</ul>
					</div>
					<div class="gtco-widget">
						<h3>Get Social</h3>
						<ul class="gtco-social-icons">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-12 text-center copyright">
					<p><small class="block">&copy; 2017 复旦大学计算机学院团学联青志实践中心 All Rights Reserved.</small>
				</div>

			</div>
		</div>
	</footer>
	<!-- </div> -->

	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>

	<!-- jQuery -->
	<script src="{%static "js/jquery.min.js"%}"></script>
	<!-- jQuery Easing -->
	<script src="{%static "js/jquery.easing.1.3.js"%}"></script>
	<!-- Bootstrap -->
	<script src="{%static "js/bootstrap.min.js"%}"></script>
	<!-- Waypoints -->
	<script src="{%static "js/jquery.waypoints.min.js"%}"></script>
	<!-- Carousel -->
	<script src="{%static "js/owl.carousel.min.js"%}"></script>
	<!-- countTo -->
	<script src="{%static "js/jquery.countTo.js"%}"></script>

	<!-- Stellar Parallax -->
	<script src="{%static "js/jquery.stellar.min.js"%}"></script>

	<!-- Magnific Popup -->
	<script src="{%static "js/jquery.magnific-popup.min.js"%}"></script>
	<script src="{%static "js/magnific-popup-options.js"%}"></script>

	<script src="{%static "js/moment.min.js"%}"></script>
	<script src="{%static "js/bootstrap-datetimepicker.min.js"%}"></script>


	<!-- Main -->
	<script src="{%static "js/main.js"%}"></script>

	</body>
</html>

startproject/appointment/templates/appointment/lecture-detail.html
<!DOCTYPE HTML>

<html xmlns="http://www.w3.org/1999/html">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>讲座详细信息</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="复旦大学计算机科学技术学院与上海高中交流辅导平台" />
	<meta name="author" content="Caroline" />

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

    {%load staticfiles%}

	<!-- Animate.css -->
	<link rel="stylesheet" href="{%static "css/animate.css"%}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{%static "css/icomoon.css"%}">
	<!-- Themify Icons-->
	<link rel="stylesheet" href="{%static "css/themify-icons.css"%}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{%static "css/bootstrap.css"%}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{%static "css/magnific-popup.css"%}">

	<!-- Bootstrap DateTimePicker -->
	<link rel="stylesheet" href="{%static "css/bootstrap-datetimepicker.min.css"%}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{%static "css/owl.carousel.min.css"%}">
	<link rel="stylesheet" href="{%static "css/owl.theme.default.min.css"%}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{%static "css/style.css"%}">

	<!-- Modernizr JS -->
	<script src="{%static "js/modernizr-2.6.2.min.js"%}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{%static "js/respond.min.js"%}"></script>
	<![endif]-->

	</head>
	<body>

	<div class="gtco-loader"></div>

	<div id="page">

	<!-- <div class="page-inner"> -->
	<nav class="gtco-nav" role="navigation">
		<div class="gtco-container">
			<div class="row">
				<div class="col-sm-4 col-xs-12">
					<div id="gtco-logo"><a href="http://127.0.0.1:8000/register/index">Computer Science <em>.</em></a></div>
				</div>
				<div class="col-xs-8 text-right menu-1">
					<ul>
						<li><a href="http://127.0.0.1:8000/news">News</a></li>
						<li class="has-dropdown">
							<a href="services.html">Appointment</a>
							<ul class="dropdown">
								<li><a href="http://127.0.0.1:8000/appointment/acm/">ACM Tutoring</a></li>
								<li><a href="http://127.0.0.1:8000/appointment/lecture/">Lecture</a></li>
								<li><a href="http://127.0.0.1:8000/appointment/station/">Science and Technology Station</a></li>
							</ul>
						</li>
                        <li><a href="contact.html">Contact</a></li>
						<li class="btn-cta"><a href="http://127.0.0.1:8000/register/"><span>Log out</span></a></li>
					</ul>
				</div>
			</div>

		</div>
	</nav>


		<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(/static/images/lecture_background.jpg)" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">

					<div class="row row-mt-15em">
						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
							<span class="intro-text-small">Created by <a target="_blank">Caroline</a></span>
							<h1 class="cursive-font">Coding makes me happy!</h1>
						</div>
					</div>

				</div>
			</div>
		</div>
	</header>

        <div id="gtco-counter" class="gtco-section">
		<div class="gtco-container">

			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading animate-box">
					<h2 class="cursive-font primary-color">Lectures details</h2>
					<p>Some information.</p>
				</div>
			</div>

			<div class="row">
                <div class="col-sm-12 col-md-4 col-lg-4" >
                    <div class="thumbnail">
                        <a href="#" title="' . $result['StuNAME'] . '" target="_blank">
                            <img id = "lecture-img{{lecture.id}}" src="{%static 'images/lecture_'%}" alt="Image" class="img-responsive" >
                                <script>
                                    document.getElementById("lecture-img{{lecture.id}}").src+={{ lecture.id }}+'.jpg'
                                </script>
                        </a>
                        <div class="caption">
                            <h3 style="display:inline-block">
                                <a href="#" title="{{lecture.theme}}" target="_blank">
                                    {{lecture.theme}}
                                </a>
                            </h3>
                            <h5>Professore: {{lecture.professor}}<br></h5>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-8 col-lg-8" style="padding-right: 50px">
                    <hr>
                    <div  style="margin-bottom: 30px">
                        <p>
                            讲座信息：{{ lecture.introduction }}</p>
                    </div>
                    <hr>

					<p> 预约该讲座： <br></p>
					<form action="{% url 'appointment:lecture_get_detail' lecture.id %}"  method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="input-field" style="padding-top: 10px">
                            {{ field.label }}: {{ field }}
                        </div>
                        <div class="error" style="color: red;">
                            {{ field.errors }}
                        </div>
                        {% endfor %}
                        <button class="btn btn-primary" type="submit" onclick="alert('预约成功！');" style="margin-top: 15px">预约</button>
                    </form>
                </div>
			</div>
		</div>
	</div>


	<footer id="gtco-footer" role="contentinfo" style="background-image: url(/static/images/img_bg_1.jpg)" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row row-pb-md">

				<div class="col-md-12 text-center">
					<div class="gtco-widget">
						<h3>Get In Touch</h3>
						<ul class="gtco-quick-contact">
							<li><a href="#"><i class="icon-phone"></i> +1 234 567 890</a></li>
							<li><a href="#"><i class="icon-mail2"></i> rshcaroline@163.com</a></li>
							<li><a href="#"><i class="icon-chat"></i> Live Chat</a></li>
						</ul>
					</div>
					<div class="gtco-widget">
						<h3>Get Social</h3>
						<ul class="gtco-social-icons">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-12 text-center copyright">
					<p><small class="block">&copy; 2017 复旦大学计算机学院团学联青志实践中心 All Rights Reserved.</small>
				</div>

			</div>
		</div>
	</footer>
	<!-- </div> -->

	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>

	<!-- jQuery -->
	<script src="{%static "js/jquery.min.js"%}"></script>
	<!-- jQuery Easing -->
	<script src="{%static "js/jquery.easing.1.3.js"%}"></script>
	<!-- Bootstrap -->
	<script src="{%static "js/bootstrap.min.js"%}"></script>
	<!-- Waypoints -->
	<script src="{%static "js/jquery.waypoints.min.js"%}"></script>
	<!-- Carousel -->
	<script src="{%static "js/owl.carousel.min.js"%}"></script>
	<!-- countTo -->
	<script src="{%static "js/jquery.countTo.js"%}"></script>

	<!-- Stellar Parallax -->
	<script src="{%static "js/jquery.stellar.min.js"%}"></script>

	<!-- Magnific Popup -->
	<script src="{%static "js/jquery.magnific-popup.min.js"%}"></script>
	<script src="{%static "js/magnific-popup-options.js"%}"></script>

	<script src="{%static "js/moment.min.js"%}"></script>
	<script src="{%static "js/bootstrap-datetimepicker.min.js"%}"></script>


	<!-- Main -->
	<script src="{%static "js/main.js"%}"></script>

	</body>
</html>