startproject/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^register/', include('register.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls')),
    url(r'^appointment/', include('appointment.urls')),
]

startproject/news/urls.py
from django.conf.urls import url

from . import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.get_news, name='news_get_news'),
    url(r'^detail/(\d+)/$', views.get_detail, name='news_get_detail'),
]

startproject/news/models.py
# Create your models here.

from django.db import models


class Category(models.Model):
    """
    分类
    """

    name = models.CharField('名称', max_length=16)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签
    """

    name = models.CharField('名称', max_length=16)

    def __str__(self):
        return self.name


class News(models.Model):
    """
    新闻
    """

    title = models.CharField('标题', max_length=32)
    author = models.CharField('作者', max_length=16)
    content = models.TextField('正文')
    created = models.DateTimeField('发布时间', auto_now_add=True)

    category = models.ForeignKey(Category, verbose_name='分类')
    tags = models.ManyToManyField(Tag, verbose_name='标签')

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    评论
    """

    news = models.ForeignKey(News, verbose_name='新闻')

    name = models.CharField('称呼', max_length=16)
    email = models.EmailField('邮箱')
    content = models.CharField('内容', max_length=140)

    created = models.DateTimeField('发布时间', auto_now_add=True)

    def __str__(self):
        return self.name

startproject/news/forms.py
from django import forms


class CommentForm(forms.Form):
    """
    评论表单
    """

    name = forms.CharField(label='称呼', max_length=16, error_messages={
        'required': '请填写您的称呼',
        'max_length': '称呼太长'
    })

    email = forms.EmailField(label='邮箱', error_messages={
        'required': '请填写您的邮箱',
        'invalid': '邮箱格式不正确'
    })

    content = forms.CharField(label='评论', error_messages={
        'required': '请填写您的评论内容',
        'max_length': '评论内容太长'
    })

startproject/news/views.py
# Create your views here.

from django.shortcuts import get_object_or_404, render
from django.http import Http404
from .forms import CommentForm

from .models import News
from .models import Comment, Tag, Category

def get_news(request):
    ctx = {
        'news': News.objects.all().order_by('-created'),
        'tags': Tag.objects.all(),
        'category': Category.objects.all()
    }
    return render(request, 'news/news-list.html', ctx)
'''
这里，我们使用了 Django 的 ORM 对博客数据进行查询，并依发布时间的倒序进行排列
然后将结果集（一个 QuerySet 对象）放在一个字典对象 ctx 的 news 中。
然后调用 render 方法来渲染模板，其第一个参数始终接收 request 对象，第二个参数是要渲染的模板文件，第三个参数则是可选的上下文参数。
注意观察视图函数的入参，其第一个参数一定是 request 对象，“这是一个不变的真理”。
'''

def get_detail(request, news_id):
    name = request.session.get('username','')
    try:
        news = News.objects.get(id=news_id)
    except News.DoesNotExist:
        raise Http404

    if request.method == 'GET':
        form = CommentForm(
            initial={'name': name}
        )
    else:
        form = CommentForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            cleaned_data['news'] = news
            Comment.objects.create(**cleaned_data)

    ctx = {
        'news': news,
        'comments': news.comment_set.all().order_by('-created'),
        'form': form,
        'tags': Tag.objects.all(),
        'category': Category.objects.all()
    }
    return render(request, 'news/news-detail.html', ctx)

startproject/news/templates/news/news-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ news.title }}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    {%load staticfiles%}

    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="{%static "news_inside/css/bootstrap.min.css"%}">

    <!-- Font-Awesome -->
    <link rel="stylesheet" href="{%static "news_inside/css/font-awesome/css/font-awesome.min.css"%}">

    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600|PT+Serif:400,400italic' rel='stylesheet' type='text/css'>

    <!-- Styles -->
   <link rel="stylesheet" href="{%static "news_inside/css/style.css"%}" id="theme-styles">

    <!--[if lt IE 9]>
        <script src="js/vendor/google/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->


</head>
<body>
    <header>
        <div class="widewrapper masthead">
            <div class="container">
                <a href="#" id="logo">
                    <img src="{%static "news_inside/img/logo.png"%}" alt="clean Blog">
                </a>

                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".clean-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>

                <nav class="pull-right clean-nav">
                    <div class="collapse navbar-collapse">
                        <ul class="nav nav-pills navbar-nav">

                             <li>
                                <a href="http://127.0.0.1:8000/register/index">Home</a>
                            </li>
                            <li>
                                <a href="contact.html">Contact</a>
                            </li>
                            <li>
                                <a href="http://127.0.0.1:8000/register/">Log out</a>
                            </li>
                        </ul>
                    </div>
                </nav>

            </div>
        </div>

        <div class="widewrapper subheader">
            <div class="container">
                <div class="clean-breadcrumb">
                    <a href="{% url 'news:news_get_news' %}">News</a>
                    <span class="separator">&#x2F;</span>
                    <a href="#">{{ news.category.name }}</a>
                </div>


                <div class="clean-searchbox">
                    <form action="#" method="get" accept-charset="utf-8">

                        <input class="searchfield" id="searchbox" type="text" placeholder="Search">
                         <button class="searchbutton" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <div class="widewrapper main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 blog-main">
                    <article class="blog-post">
                        <header>

                            <div class="lead-image">
                                <img id = "news-img{{news.id}}" src="{%static 'news_inside/img/'%}" alt="">
                                    <script>
                                        document.getElementById("news-img{{news.id}}").src+={{ news.id }}+'.jpg'
                                    </script>
                            </div>
                        </header>
                        <div class="body">
                            <h2>{{ news.title }}</h2>
                            <div class="meta">
                                <i class="fa fa-user"></i> {{ news.author }} <i class="fa fa-calendar"></i>{{ news.created|date:"Y-m-d H:i" }}<i class="fa fa-comments"></i><span class="data"><a href="#comments"> Comments</a></span>
                            </div>

                            <div class="summary">
                                {{ news.content }}
                            </div>

                        </div>
                    </article>

                    <aside class="social-icons clearfix">
                        <h3>Share on </h3>
                        <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-google"></i></a>
                    </aside>

                    <aside class="comments" id="comments">
                        <hr>

                        <h2><i class="fa fa-comments"></i> Comments</h2>

                        <article class="comment">
                            {% for comment in comments %}
                            <header class="clearfix">
                                <img src="{%static "news_inside/img/avatar.png"%}" alt="A Smart Guy" class="avatar">
                                <div class="meta">
                                    <h3><a href="#">{{ comment.name }}</a></h3>
                                    <span class="date">
                                        {{ comment.created }}
                                    </span>
                                    <span class="separator">
                                        -
                                    </span>

                                    <a href="#create-comment" class="reply-link">Reply</a>
                                </div>
                            </header>
                             <div class="body">
                                 {{ comment.content }}
                             </div>
                            {% endfor %}
                        </article>

                    </aside>

                    <aside class="create-comment" id="create-comment">
                        <hr>
                        <h2><i class="fa fa-pencil"></i> Add Comment</h2>

                        <div style="padding-left: 270px">
                            <form action="{% url 'news:news_get_detail' news.id %}" method="post">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="input-field" style="padding-top: 10px">
                                {{ field.label }}: {{ field }}
                            </div>
                            <div class="error" style="color: red;">
                                {{ field.errors }}
                            </div>
                            {% endfor %}
                            <div class="col-xs-6">
                                <p>  </p>
                                <button type="submit" class="btn btn-success" style="margin-top: 10px">提交</button>
                            </div>
                        </form>
                        </div>


                        <!---
                        <form action="#" method="get" accept-charset="utf-8">
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" name="name" id="comment-name" placeholder="Your Name" class="form-control input-lg">
                                </div>
                                <div class="col-md-6">
                                    <input type="email" name="email" id="comment-email" placeholder="Email" class="form-control input-lg">
                                </div>
                            </div>

                            <textarea rows="10" name="message" id="comment-body" placeholder="Your Message" class="form-control input-lg"></textarea>

                            <div class="buttons clearfix">
                                <button type="submit" class="btn btn-xlarge btn-clean-one">Submit</button>
                            </div>
                        </form>
                        -->
                    </aside>
                </div>

                <aside class="col-md-4 blog-aside">

                    <div class="aside-widget">
                        <header>
                            <h3>Categorys</h3>
                        </header>
                        <div class="body clearfix">
                            <ul class="tags">
                                {% for category in category %}
                                    <li><a href="#">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="aside-widget">
                        <header>
                            <h3>Tags</h3>
                        </header>
                        <div class="body clearfix">
                            <ul class="tags">
                                {% for tags in tags %}
                                    <li><a href="#">{{ tags.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>

    <footer>
        <div class="widewrapper footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-user"></i>About</h3>

                        <p>© 2017 复旦大学计算机科学技术学院</p>
                        <p>地址：上海市张衡路825号</p>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-pencil"></i>Categorys</h3>
                        <div class="body clearfix">
                            <ul class="tags">
                                {% for category in category %}
                                    <li><a href="#">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-envelope"></i> Get In Touch</h3>

                        <p>Tell：+86-21-51355555</p>
                        <p>Fax：+86-21-51355558</p>
                        <p>Emall：cs_school@fudan.edu.cn</p>
                         <div class="footer-widget-icon">
                            <i class="fa fa-facebook"></i><i class="fa fa-twitter"></i><i class="fa fa-google"></i>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="widewrapper copyright">
                2017 复旦大学计算机学院团学联青志实践中心 All Rights Reserved.
        </div>
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/modernizr.js"></script>

</body>
</html>

startproject/news/templates/news/news-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>新闻速递</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    {%load staticfiles%}

    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="{%static "news_inside/css/bootstrap.min.css"%}">

    <!-- Font-Awesome -->
    <link rel="stylesheet" href="{%static "news_inside/css/font-awesome/css/font-awesome.min.css"%}">

    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600|PT+Serif:400,400italic' rel='stylesheet' type='text/css'>

    <!-- Styles -->
   <link rel="stylesheet" href="{%static "news_inside/css/style.css"%}" id="theme-styles">

    <!--[if lt IE 9]>
        <script src="js/vendor/google/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->


</head>
<body>
    <header>
        <div class="widewrapper masthead">
            <div class="container">
                <a href="#" id="logo">
                    <img src="{%static "news_inside/img/logo.png"%}" alt="clean Blog">
                </a>

                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".clean-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>

                <nav class="pull-right clean-nav">
                    <div class="collapse navbar-collapse">
                        <ul class="nav nav-pills navbar-nav">

                             <li>
                                <a href="http://127.0.0.1:8000/register/index">Home</a>
                            </li>
                            <li>
                                <a href="contact.html">Contact</a>
                            </li>
                            <li>
                                <a href="http://127.0.0.1:8000/register/">Log out</a>
                            </li>
                        </ul>
                    </div>
                </nav>

            </div>
        </div>

        <div class="widewrapper subheader">
            <div class="container">
                <div class="clean-breadcrumb">
                    <a href="#">Blog</a>
                </div>

                <div class="clean-searchbox">
                    <form action="#" method="get" accept-charset="utf-8">
                        <input class="searchfield" id="searchbox" type="text" placeholder="Search">
                        <button class="searchbutton" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </header>


    <div class="widewrapper main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 blog-main">
                        {% for news in news %}
                        <div class="">
                            <article class=" blog-teaser">
                                <header>
                                    <img id = "news-img{{news.id}}" src="{%static 'news_inside/img/'%}" alt="">
                                    <script>
                                        document.getElementById("news-img{{news.id}}").src+={{ news.id }}+'.jpg'
                                    </script>
                                    <div class="news">
                                        <div class="title">
                                            <h3><a href="{% url 'news:news_get_detail' news.id %}"><h4>{{ news.title }}</h4></a></h3>
                                        </div>
                                        <div class="info">
                                            <span class="category" style="color: #ff9900;">{{ news.category.name }}</span>
                                            <span class="created" style="color: #6aa84f">{{ news.created|date:"Y-m-d H:i" }}</span>
                                        </div>
                                        <div class="summary">
                                            {{ news.content|slice:"40" }} ...
                                        </div>
                                    </div>
                                    <hr>
                                </header>
                            </article>
                        </div>
                        {% endfor %}

                    <div class="paging">
                        <a href="#" class="older">Older Post</i></a>
                    </div>
                </div>
                <aside class="col-md-4 blog-aside">

                    <div class="aside-widget">
                        <header>
                            <h3>Categorys</h3>
                        </header>
                        <div class="body clearfix">
                            <ul class="tags">
                                {% for category in category %}
                                    <li><a href="#">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="aside-widget">
                        <header>
                            <h3>Tags</h3>
                        </header>
                        <div class="body clearfix">
                            <ul class="tags">
                                {% for tags in tags %}
                                    <li><a href="#">{{ tags.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>

  <footer>
        <div class="widewrapper footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-user"></i>About</h3>

                        <p>© 2017 复旦大学计算机科学技术学院</p>
                        <p>地址：上海市张衡路825号</p>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-pencil"></i>Categorys</h3>
                        <div class="body clearfix">
                            <ul class="tags">
                                {% for category in category %}
                                    <li><a href="#">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-envelope"></i> Get In Touch</h3>

                        <p>Tell：+86-21-51355555</p>
                        <p>Fax：+86-21-51355558</p>
                        <p>Emall：cs_school@fudan.edu.cn</p>
                         <div class="footer-widget-icon">
                            <i class="fa fa-facebook"></i><i class="fa fa-twitter"></i><i class="fa fa-google"></i>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="widewrapper copyright">
                2017 复旦大学计算机学院团学联青志实践中心 All Rights Reserved.
        </div>
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/modernizr.js"></script>
<script>

</script>

</body>
</html>